# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 25.x
      uses: actions/setup-node@v4
      with:
        node-version: 25.x
        cache: 'npm'
    - name: Install node_modules
      run: npm install 
    - name: Start Server, Build and Run Tests
      run: npm run server &
    - name: Start app
      run: npm run start &
    - name: Install playwright browsers
      run: npx playwright install
    - name: Start Tests
      run: npm test